test: Fix build issue with missing _GNU_SOURCE
  CC       ell/test.lo
ell/test.c: In function 'test_setup':
ell/test.c:209:23: error: implicit declaration of function 'setenv'; did you mean 'getenv'? [-Wimplicit-function-declaration]
  209 |                 err = setenv("DBUS_SYSTEM_BUS_ADDRESS", test->dbus_address, 1);
      |                       ^~~~~~
      |                       getenv
ell/test.c: In function 'test_teardown':
ell/test.c:310:25: error: implicit declaration of function 'kill' [-Wimplicit-function-declaration]
  310 |                         kill(test->dbus_pid, SIGKILL);
      |                         ^~~~
ell/test.c: In function 'l_test_run':
ell/test.c:463:9: error: implicit declaration of function 'sigemptyset' [-Wimplicit-function-declaration]
  463 |         sigemptyset(&sig_mask);
      |         ^~~~~~~~~~~
ell/test.c:464:9: error: implicit declaration of function 'sigaddset' [-Wimplicit-function-declaration]
  464 |         sigaddset(&sig_mask, SIGINT);
      |         ^~~~~~~~~
ell/test.c:473:13: error: implicit declaration of function 'sigprocmask' [-Wimplicit-function-declaration]
  473 |         if (sigprocmask(SIG_BLOCK, &sig_mask, &old_mask) < 0)
      |             ^~~~~~~~~~~
ell/test.c:473:25: error: 'SIG_BLOCK' undeclared (first use in this function)
  473 |         if (sigprocmask(SIG_BLOCK, &sig_mask, &old_mask) < 0)
      |                         ^~~~~~~~~
ell/test.c:473:25: note: each undeclared identifier is reported only once for each function it appears in
ell/test.c:478:29: error: 'SIG_SETMASK' undeclared (first use in this function)
  478 |                 sigprocmask(SIG_SETMASK, &old_mask, NULL);
      |                             ^~~~~~~~~~~

  CC       ell/test-dbus.lo
ell/test-dbus.c: In function 'fork_broker':
ell/test-dbus.c:97:24: error: implicit declaration of function 'alloca'; did you mean 'calloc'? [-Wimplicit-function-declaration]
   97 |                 argv = alloca(sizeof(char *) * 12);
      |                        ^~~~~~
      |                        calloc
ell/test-dbus.c:97:22: error: assignment to 'char **' from 'int' makes pointer from integer without a cast [-Wint-conversion]
   97 |                 argv = alloca(sizeof(char *) * 12);
      |                      ^
ell/test-dbus.c:110:22: error: assignment to 'char **' from 'int' makes pointer from integer without a cast [-Wint-conversion]
  110 |                 envp = alloca(sizeof(char *) * 4);
      |                      ^
ell/test-dbus.c: In function 'start_dbus':
ell/test-dbus.c:256:17: error: implicit declaration of function 'kill' [-Wimplicit-function-declaration]
  256 |                 kill(pid, SIGKILL);
      |                 ^~~~