unit: Fix build issue with missing _GNU_SOURCE
  CC       unit/test-minheap.o
unit/test-minheap.c: In function ‘test_minheap_init’:
unit/test-minheap.c:64:23: error: implicit declaration of function ‘alloca’; did you mean ‘calloc’? [-Wimplicit-function-declaration]
   64 |         int *values = alloca(sizeof(test_values));
      |                       ^~~~~~
      |                       calloc
unit/test-minheap.c:64:23: error: initialization of ‘int *’ from ‘int’ makes pointer from integer without a cast [-Wint-conversio]
In file included from ./ell/ell.h:8,
                 from unit/test-minheap.c:17:
unit/test-minheap.c: In function ‘test_minheap_push’:
./ell/util.h:303:21: error: assignment to ‘void *’ from ‘int’ makes pointer from integer without a cast [-Wint-conversion]
  303 |                 __p = alloca(__n * __s);        \
      |                     ^
unit/test-minheap.c:77:23: note: in expansion of macro ‘l_newa’
   77 |         int *values = l_newa(int, L_ARRAY_SIZE(test_values));
      |                       ^~~~~~
unit/test-minheap.c: In function ‘test_minheap_push_random’:
unit/test-minheap.c:98:34: error: implicit declaration of function ‘random’; did you mean ‘rand’? [-Wimplicit-function-declaratio]
   98 |                 unsigned int r = random();
      |                                  ^~~~~~
      |                                  rand
unit/test-minheap.c: In function ‘test_minheap_pop_push’:
unit/test-minheap.c:110:23: error: initialization of ‘int *’ from ‘int’ makes pointer from integer without a cast [-Wint-conversion]
  110 |         int *values = alloca(sizeof(test_values));
      |                       ^~~~~~
unit/test-minheap.c: In function ‘test_minheap_delete’:
./ell/util.h:303:21: error: assignment to ‘void *’ from ‘int’ makes pointer from integer without a cast [-Wint-conversion]
  303 |                 __p = alloca(__n * __s);        \
      |                     ^
unit/test-minheap.c:133:23: note: in expansion of macro ‘l_newa’
  133 |         int *values = l_newa(int, L_ARRAY_SIZE(test_values));
      |                       ^~~~~~