cert: Fix build issue with missing _GNU_SOURCE
  CC       ell/cert.lo
ell/cert.c: In function 'cert_key_from_pkcs8_encrypted_private_key_info':
ell/cert.c:941:9: error: implicit declaration of function 'explicit_bzero' [-Wimplicit-function-declaration]
  941 |         explicit_bzero(decrypted, data_len);
      |         ^~~~~~~~~~~~~~