acd: Fix build issue with missing _GNU_SOURCE
  CC       ell/acd.lo
ell/acd.c: In function 'acd_send_packet':
ell/acd.c:114:26: error: storage size of 'p' isn't known
  114 |         struct ether_arp p;
      |                          ^
In file included from /usr/include/arpa/inet.h:22,
                 from ell/acd.c:17:
ell/acd.c:128:27: error: 'ETHERTYPE_IP' undeclared (first use in this function)
  128 |         p.arp_pro = htons(ETHERTYPE_IP);
      |                           ^~~~~~~~~~~~
ell/acd.c:128:27: note: each undeclared identifier is reported only once for each function it appears in
ell/acd.c:114:26: error: unused variable 'p' [-Werror=unused-variable]
  114 |         struct ether_arp p;
      |                          ^
ell/acd.c: In function 'acd_read_handler':
ell/acd.c:249:26: error: storage size of 'arp' isn't known
  249 |         struct ether_arp arp;
      |                          ^~~
ell/acd.c:249:26: error: unused variable 'arp' [-Werror=unused-variable]