net: Fix build issue with missing strings.h include
  CC       ell/net.lo
ell/net.c: In function 'str_has_suffix':
ell/net.c:143:17: error: implicit declaration of function 'strcasecmp'; did you mean 'strncmp'? [-Wimplicit-function-declaration]
  143 |         return !strcasecmp(&str[len_diff], suffix);
      |                 ^~~~~~~~~~
      |                 strncmp